name: skilled_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.17+17

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_clean_calendar: ^1.1.0
  flutter_onboard: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_share: null
  flutter_switch: 0.3.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_typeahead: ^3.2.3
  get: ^4.6.1
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+11
  multi_select_flutter: ^4.0.0
  percent_indicator: ^4.0.0
  pinput: null
  responsive_framework: ^0.2.0
  rounded_linear_progress: ^0.0.2
  share_plus: null
  swipe: ^0.0.1
  swipeable_page_route: ^0.2.6
  textfield_tags: ^1.4.2
  url_launcher: null
  video_player: ^2.4.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/skilldlogo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
